### ISSUE TITLE
ccbr1187 data run

### ISSUE THREAD

**Issue by kopardev** [CCBR/CHAMPAGNE#122]
### Description of feature

Run real project data from ccbr1187

**Comment by kelly-sovacool** [comment]
Comparing read counts to old pipeliner:

|SampleName              |name             | value_orig| value_new| rel_diff_percent|
|:-----------------------|:----------------|----------:|---------:|----------------:|
|D1_Input_1              |NReads           |  204412055| 408824110|           100.00|
|D1_Input_1              |NMappedReads     |  349471104| 350597036|             0.32|
|D1_Input_1              |NUniqMappedReads |  257039206| 257799730|             0.30|
|D1_Input_2              |NReads           |  226555465| 453110930|           100.00|
|D1_Input_2              |NMappedReads     |  386415459| 387629277|             0.31|
|D1_Input_2              |NUniqMappedReads |  286596196| 287446152|             0.30|
|D1_P7+TLX3_STAT5_1      |NReads           |   72630765| 145261530|           100.00|
|D1_P7+TLX3_STAT5_1      |NMappedReads     |  120574446| 120938735|             0.30|
|D1_P7+TLX3_STAT5_1      |NUniqMappedReads |   84420590|  84675786|             0.30|
|D1_P7+TLX3_STAT5_2      |NReads           |   70185244| 140370488|           100.00|
|D1_P7+TLX3_STAT5_2      |NMappedReads     |  117360597| 117725501|             0.31|
|D1_P7+TLX3_STAT5_2      |NUniqMappedReads |   84018510|  84258946|             0.29|
|D1_P7+TLX3_TLX3_1       |NReads           |   64765059| 129530118|           100.00|
|D1_P7+TLX3_TLX3_1       |NMappedReads     |  105354661| 105703353|             0.33|
|D1_P7+TLX3_TLX3_1       |NUniqMappedReads |   71413146|  71643278|             0.32|
|D1_P7+TLX3_TLX3_2       |NReads           |   64838609| 129677218|           100.00|
|D1_P7+TLX3_TLX3_2       |NMappedReads     |  107182187| 107525051|             0.32|
|D1_P7+TLX3_TLX3_2       |NUniqMappedReads |   75891666|  76122192|             0.30|
|D1_P7+TLX3_TLX3_Input_3 |NReads           |  211456008| 422912016|           100.00|
|D1_P7+TLX3_TLX3_Input_3 |NMappedReads     |  351106840| 352200524|             0.31|
|D1_P7+TLX3_TLX3_Input_3 |NUniqMappedReads |  259883902| 260614698|             0.28|
|D1_P7+TLX3_TLX3_Input_4 |NReads           |  208845700| 417691400|           100.00|
|D1_P7+TLX3_TLX3_Input_4 |NMappedReads     |  349017095| 350089273|             0.31|
|D1_P7+TLX3_TLX3_Input_4 |NUniqMappedReads |  260652520| 261399180|             0.29|
|D1_STAT5_1              |NReads           |   73454435| 146908870|           100.00|
|D1_STAT5_1              |NMappedReads     |  125567570| 125983941|             0.33|
|D1_STAT5_1              |NUniqMappedReads |   87170772|  87452850|             0.32|
|D1_STAT5_2              |NReads           |   63886275| 127772550|           100.00|
|D1_STAT5_2              |NMappedReads     |  109588855| 109952094|             0.33|
|D1_STAT5_2              |NUniqMappedReads |   76737298|  76980324|             0.32|
|D1_TLX3_1               |NReads           |   63979497| 127958994|           100.00|
|D1_TLX3_1               |NMappedReads     |  109400016| 109757618|             0.33|
|D1_TLX3_1               |NUniqMappedReads |   77164758|  77403410|             0.31|
|D1_TLX3_2               |NReads           |   59299793| 118599586|           100.00|
|D1_TLX3_2               |NMappedReads     |  101453518| 101781981|             0.32|
|D1_TLX3_2               |NUniqMappedReads |   72115790|  72337222|             0.31|

**Comment by kelly-sovacool** [comment]
peak counts are lower than they should be

|sample_id          |tool        | count_old| count_new| rel_diff_percent|
|:------------------|:-----------|---------:|---------:|----------------:|
|D1_P7+TLX3_STAT5_1 |gem         |      4337|      2233|           -48.51|
|D1_P7+TLX3_STAT5_2 |gem         |      1303|       807|           -38.07|
|D1_P7+TLX3_TLX3_1  |gem         |      1373|       869|           -36.71|
|D1_P7+TLX3_TLX3_2  |gem         |      1281|       581|           -54.64|
|D1_STAT5_1         |gem         |      2723|      1223|           -55.09|
|D1_STAT5_2         |gem         |      1179|       663|           -43.77|
|D1_TLX3_1          |gem         |       977|       795|           -18.63|
|D1_TLX3_2          |gem         |      1190|       771|           -35.21|
|D1_P7+TLX3_STAT5_1 |macs_broad  |      2223|       210|           -90.55|
|D1_P7+TLX3_STAT5_2 |macs_broad  |       491|       143|           -70.88|
|D1_P7+TLX3_TLX3_1  |macs_broad  |       113|        19|           -83.19|
|D1_P7+TLX3_TLX3_2  |macs_broad  |       160|        20|           -87.50|
|D1_STAT5_1         |macs_broad  |     18171|       157|           -99.14|
|D1_STAT5_2         |macs_broad  |       392|       131|           -66.58|
|D1_TLX3_1          |macs_broad  |       422|         2|           -99.53|
|D1_TLX3_2          |macs_broad  |       114|         6|           -94.74|
|D1_P7+TLX3_STAT5_1 |macs_narrow |      2075|       178|           -91.42|
|D1_P7+TLX3_STAT5_2 |macs_narrow |       467|       124|           -73.45|
|D1_P7+TLX3_TLX3_1  |macs_narrow |       114|        14|           -87.72|
|D1_P7+TLX3_TLX3_2  |macs_narrow |       145|        14|           -90.34|
|D1_STAT5_1         |macs_narrow |     15231|       126|           -99.17|
|D1_STAT5_2         |macs_narrow |       372|       107|           -71.24|
|D1_TLX3_1          |macs_narrow |       372|         2|           -99.46|
|D1_TLX3_2          |macs_narrow |        91|         5|           -94.51|
|D1_P7+TLX3_STAT5_1 |sicer       |     43949|     66942|            52.32|
|D1_P7+TLX3_STAT5_2 |sicer       |     18063|     35309|            95.48|
|D1_P7+TLX3_TLX3_1  |sicer       |     17267|     32213|            86.56|
|D1_P7+TLX3_TLX3_2  |sicer       |     16871|     34259|           103.06|
|D1_STAT5_1         |sicer       |     45753|     51428|            12.40|
|D1_STAT5_2         |sicer       |     25164|     29108|            15.67|
|D1_TLX3_1          |sicer       |     31466|     36199|            15.04|
|D1_TLX3_2          |sicer       |     28301|     43853|            54.95|
