### ISSUE TITLE
List of test datasets

### ISSUE THREAD

**Issue by kopardev** [CCBR/CHAMPAGNE#165]
## 1. TF narrow peaks CTCF in human 
- [3 replicates](https://www.encodeproject.org/experiments/ENCSR414CQB/) IP
- [3 replicates](https://www.encodeproject.org/experiments/ENCSR382EJS/) Input
- Part of a larger time series [dataset](https://www.encodeproject.org/treatment-time-series/ENCSR738NGQ/)
- Found using [these filters](https://www.encodeproject.org/search/?type=Experiment&assay_term_name=ChIP-seq&status=released&assay_title=TF+ChIP-seq&replication_type=isogenic&audit.WARNING.category%21=inconsistent+platforms&audit.WARNING.category%21=borderline+replicate+concordance&audit.WARNING.category%21=mild+to+moderate+bottlenecking&audit.WARNING.category%21=missing+genetic+modification+reagents&audit.WARNING.category%21=moderate+library+complexity&audit.WARNING.category%21=antibody+characterized+with+exemption&audit.NOT_COMPLIANT.category%21=insufficient+read+depth&audit.NOT_COMPLIANT.category%21=partially+characterized+antibody&audit.NOT_COMPLIANT.category%21=insufficient+read+length&audit.NOT_COMPLIANT.category%21=control+insufficient+read+depth&replication_type%21=unreplicated&target.label=CTCF)

## 2. TF narrow peaks JUN in human
- [3 IP replicates](https://www.encodeproject.org/experiments/ENCSR604CKQ/)
- [3 Input replicates](https://www.encodeproject.org/experiments/ENCSR344CSQ/)
- Found using [these filters](https://www.encodeproject.org/search/?type=Experiment&assay_term_name=ChIP-seq&status=released&assay_title=TF+ChIP-seq&replication_type=isogenic&audit.WARNING.category%21=inconsistent+platforms&audit.WARNING.category%21=borderline+replicate+concordance&audit.WARNING.category%21=mild+to+moderate+bottlenecking&audit.WARNING.category%21=missing+genetic+modification+reagents&audit.WARNING.category%21=moderate+library+complexity&audit.WARNING.category%21=antibody+characterized+with+exemption&audit.NOT_COMPLIANT.category%21=insufficient+read+depth&audit.NOT_COMPLIANT.category%21=partially+characterized+antibody&audit.NOT_COMPLIANT.category%21=insufficient+read+length&audit.NOT_COMPLIANT.category%21=control+insufficient+read+depth&replication_type%21=unreplicated&target.label=JUN)

## 3. H3K4me3 narrow promoter peaks in human
- [2 IP replicates](https://www.encodeproject.org/experiments/ENCSR261LYD/)
- [2 Input replicates](https://www.encodeproject.org/experiments/ENCSR354HOM/)
- Found using [these filters](https://www.encodeproject.org/search/?type=Experiment&assay_term_name=ChIP-seq&status=released&replication_type=isogenic&audit.WARNING.category!=inconsistent+platforms&audit.WARNING.category!=borderline+replicate+concordance&audit.WARNING.category!=mild+to+moderate+bottlenecking&audit.WARNING.category!=missing+genetic+modification+reagents&audit.WARNING.category!=moderate+library+complexity&audit.WARNING.category!=antibody+characterized+with+exemption&audit.NOT_COMPLIANT.category!=insufficient+read+depth&audit.NOT_COMPLIANT.category!=partially+characterized+antibody&audit.NOT_COMPLIANT.category!=insufficient+read+length&audit.NOT_COMPLIANT.category!=control+insufficient+read+depth&replication_type!=unreplicated&assay_title=Histone+ChIP-seq&target.label=H3K4me3)

## 4. H3K27ac enhancer (mixed=narrow+broad) peaks in human
- [2 IP replicates](https://www.encodeproject.org/experiments/ENCSR451WXC/)
- [2 Input replicates](https://www.encodeproject.org/experiments/ENCSR354HOM/) (same as above.)
- Found using [these filters](https://www.encodeproject.org/search/?type=Experiment&assay_term_name=ChIP-seq&status=released&replication_type=isogenic&audit.WARNING.category!=inconsistent+platforms&audit.WARNING.category!=borderline+replicate+concordance&audit.WARNING.category!=mild+to+moderate+bottlenecking&audit.WARNING.category!=missing+genetic+modification+reagents&audit.WARNING.category!=moderate+library+complexity&audit.WARNING.category!=antibody+characterized+with+exemption&audit.NOT_COMPLIANT.category!=insufficient+read+depth&audit.NOT_COMPLIANT.category!=partially+characterized+antibody&audit.NOT_COMPLIANT.category!=insufficient+read+length&audit.NOT_COMPLIANT.category!=control+insufficient+read+depth&replication_type!=unreplicated&assay_title=Histone+ChIP-seq&target.label=H3K27ac)

## 5. H3K36me3 broad peaks in human associated with [heterochromatin](https://www.sciencedirect.com/topics/biochemistry-genetics-and-molecular-biology/heterochromatin)
- [2 IP replicates](https://www.encodeproject.org/experiments/ENCSR687MPF/)
- [2 Input replicates](https://www.encodeproject.org/experiments/ENCSR354HOM/) (same as above.)
- Found using [these filters](https://www.encodeproject.org/search/?type=Experiment&assay_term_name=ChIP-seq&status=released&replication_type=isogenic&audit.WARNING.category!=inconsistent+platforms&audit.WARNING.category!=borderline+replicate+concordance&audit.WARNING.category!=mild+to+moderate+bottlenecking&audit.WARNING.category!=missing+genetic+modification+reagents&audit.WARNING.category!=moderate+library+complexity&audit.WARNING.category!=antibody+characterized+with+exemption&audit.NOT_COMPLIANT.category!=insufficient+read+depth&audit.NOT_COMPLIANT.category!=partially+characterized+antibody&audit.NOT_COMPLIANT.category!=insufficient+read+length&audit.NOT_COMPLIANT.category!=control+insufficient+read+depth&replication_type!=unreplicated&assay_title=Histone+ChIP-seq&target.label=H3K36me3)

**Comment by kopardev** [comment]
@kelly-sovacool:
- Download these from SRA
- systematically call peaks
- use them for testing pipeline
- use them for testing RECAP + MSPC strategy

**Comment by kelly-sovacool** [comment]
For differential analysis, use dataset 1 and pick two time points. Check out the paper to compare results.

**Comment by kelly-sovacool** [comment]
For all, compare peak calls to Encode peaks (macs2)

**Comment by kelly-sovacool** [comment]
- Compare peak overlaps between champagne and encode wtih Intervene
- Use [MEME FIMO](https://meme-suite.org/meme/doc/fimo.html) to determine unique peaks that contain the motif. Are we missing peaks, is encode missing peaks?

**Comment by kelly-sovacool** [comment]
![TF ChIP-seq graph](https://github.com/user-attachments/assets/da85a0d6-57c2-45d4-bd89-f5bbbf3be4fa)

![Histone ChIP-seq graph](https://github.com/user-attachments/assets/d7df1cf1-ccaa-4477-80e2-c7b46c47d4b5)
