### ISSUE TITLE
change {params.contrast} to be TRUE/FALSE rather than input file

### ISSUE THREAD

**Issue by slsevilla** [CCBR/CHAMPAGNE#196]
### Description of the bug

Pipeline does not have to include contrasts, even though it might well be included the majority of time. Need to have two variables.

```
1) {params.contrast} default to FALSE
2) {params.contrastsheet} default to null
```

1) will allow us to determine whether or not to run contrastsheet check
2) will be an absolute path to the contrast manifest

**Comment by slsevilla** [comment]
The issue was that you can't have a file set to null, so this was failing:
```
INPUT_CHECK(file(params.input, checkIfExists: true), params.seq_center, file(contrastsheet))
```

I figured out I could actually avoid the duplicate variable by adding 
```
contrastsheet = params.contrastsheet ?: "/assets/contrast_test.ymls"
```
and so we don't actually need both variables anymore. i forgot to remove and update.

**Comment by kelly-sovacool** [comment]
gotcha! thanks for figuring out a solution

**Comment by kelly-sovacool** [comment]
Instead, let's use one param for `contrastsheet` and check whether the value is null. This way we don't need two redundant params.
