### ISSUE TITLE
marnorm reading in R1 twice

### ISSUE THREAD

**Issue by slsevilla** [CCBR/CHAMPAGNE#197]
### Description of the bug

bug in manrom 

https://github.com/CCBR/CHAMPAGNE/blob/main/modules/local/manorm/main.nf

**Comment by kelly-sovacool** [comment]
looks like this should be `tagalign1` instead of `tagalign2`? https://github.com/CCBR/CHAMPAGNE/blob/d06ce0f24de44273aed31a9d00403f4e41e67f8d/modules/local/manorm/main.nf#L21
