### ISSUE TITLE
macs broad & narrow peaks are same width

### ISSUE THREAD

**Issue by kelly-sovacool** [CCBR/CHAMPAGNE#95]
with full mm10 dataset

![peak_widths_histogram](https://github.com/CCBR/CHAMPAGNE/assets/17768269/06bac138-d9ed-4225-be5d-7c854b5259ce)

**Comment by slsevilla** [comment]
Was going to comment - this happens from time to time with data that does not have broad peaks. I'm running data through now - will see if this is an issue with mine

**Comment by kelly-sovacool** [comment]
Ok that makes sense. If a dataset that should have a mixed of broad peaks (# 4 from here https://github.com/CCBR/CHAMPAGNE/issues/165#issue-2074741205) doesn't have this problem then we can close this issue.

**Comment by slsevilla** [comment]
We can close - looking at a recent project has differences between the peak callers for broad(top row) and narrow (middle row) peaks.

<img width="570" alt="Screenshot 2024-02-28 at 4 53 36 PM" src="https://github.com/CCBR/CHAMPAGNE/assets/20726305/dd22aa61-fe46-42c8-8cdb-b45ddece2f77">
 Looking at data

**Comment by slsevilla** [comment]
meant to add this too! 
![peak_widths_histogram](https://github.com/CCBR/CHAMPAGNE/assets/20726305/dd90dcbd-8082-4f35-8700-f8e61bba476a)
